"""Added Annotations replacing Community Notes

Revision ID: 20ceae3a9718
Revises: 
Create Date: 2024-11-11 19:18:07.878891

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20ceae3a9718'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable = False),
    sa.Column('processed_image_id', sa.Integer(), nullable = False),
    sa.Column('maintainer_id', sa.Integer(), nullable = False),
    sa.Column('detection_index', sa.Integer(), nullable = False),
    sa.Column('original_detection', postgresql.JSONB(astext_type = sa.Text()), nullable = False),
    sa.Column('corrected_detection', postgresql.JSONB(astext_type = sa.Text()), nullable = False),
    sa.Column('annotation_date', sa.DateTime(), nullable = False),
    sa.ForeignKeyConstraint(['maintainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_image_id'], ['processed_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('community_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_notes',
    sa.Column('id', sa.INTEGER(), autoincrement = True, nullable = False),
    sa.Column('processed_image_id', sa.INTEGER(), autoincrement = False, nullable = False),
    sa.Column('author_id', sa.INTEGER(), autoincrement = False, nullable = False),
    sa.Column('content', sa.TEXT(), autoincrement = False, nullable = False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement = False, nullable = False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name = 'community_notes_author_id_fkey'),
    sa.ForeignKeyConstraint(['processed_image_id'], ['processed_images.id'], name = 'community_notes_processed_image_id_fkey'),
    sa.PrimaryKeyConstraint('id', name = 'community_notes_pkey')
    )
    op.drop_table('annotations')
    # ### end Alembic commands ###
