"""Some changes p1

Revision ID: 277d0bc11597
Revises: 33c8d435abd4
Create Date: 2024-11-17 23:42:34.334085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '277d0bc11597'
down_revision: Union[str, None] = '33c8d435abd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_images', 'processed_date')
    op.drop_column('processed_images', 'processing_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('processing_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('processed_images', sa.Column('processed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
