"""Some changes p202

Revision ID: 35ab33bb6aeb
Revises: d27c21db9041
Create Date: 2024-11-24 23:39:20.309081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ab33bb6aeb'
down_revision: Union[str, None] = 'd27c21db9041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
