"""Some changes p201

Revision ID: d27c21db9041
Revises: fc67f5f4e8eb
Create Date: 2024-11-24 23:23:51.293732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27c21db9041'
down_revision: Union[str, None] = 'fc67f5f4e8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_images', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_images', 'image_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
