"""Some changes p7

Revision ID: ecd20464a84b
Revises: 8881dbc7c7d9
Create Date: 2024-11-21 09:44:12.928026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecd20464a84b'
down_revision: Union[str, None] = '8881dbc7c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('original_detection', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('annotations', sa.Column('corrected_detection', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_unique_constraint('unique_annotation_per_detection', 'annotations', ['processed_image_id', 'detection_index'])
    op.drop_column('annotations', 'original_metadata')
    op.drop_column('annotations', 'corrected_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('corrected_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('annotations', sa.Column('original_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint('unique_annotation_per_detection', 'annotations', type_='unique')
    op.drop_column('annotations', 'corrected_detection')
    op.drop_column('annotations', 'original_detection')
    # ### end Alembic commands ###
