"""Some changes p9

Revision ID: 1f7701ce1eeb
Revises: 47e0e5c0a50f
Create Date: 2024-11-21 09:45:21.000275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7701ce1eeb'
down_revision: Union[str, None] = '47e0e5c0a50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
