"""Some changes p199

Revision ID: 2edafbf7a943
Revises: 1f7701ce1eeb
Create Date: 2024-11-24 16:27:58.899284

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2edafbf7a943'
down_revision: Union[str, None] = '1f7701ce1eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_images', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_images', 'image_data')
    # ### end Alembic commands ###
